<?php

return [
    'form' =>
    [
        'name' => 'Default',
        'fields' =>
        [
            'firm' => null,
            'person' =>
            [
                'avatar' => false,
                'firstName' => true,
                'middleName' => false,
                'lastName' => true,
                'suffix' => false,
                'preferredName' => false,
                'priorName' => false,
                'spouse' => false,
                'birthDate' => false,
                'ethnicity' => false,
                'gender' => false,
                'pronoun' => false,
                'email' => null,
                'emailType' => false,
                'alternateEmail' => false,
                'alternateEmailType' => false,
                'emailExclude' => false,
                'phone' => false,
                'homePhone' => false,
                'mobilePhone' => false,
                'textExclude' => false,
                'officePhone' => false,
                'officeExtension' => false,
                'officeFax' => false,
                'address' =>
                [
                    'line1' => true,
                    'line2' => false,
                    'city' => true,
                    'state' => true,
                    'postalCode' => true,
                    'country' => true,
                ],
                'poAddress' =>
                [
                    'line1' => null,
                    'postalCode' => null,
                ],
                'contactPreferences' => false,
                'preferences' => false,
                'publicRegistration' => false,
                'social' => false,
                'links' =>
                [
                    'facebook' => false,
                    'instagram' => false,
                    'linkedin' => false,
                    'twitter' => false,
                ],
                'educational' => false,
                'school' => false,
                'schoolName' => false,
                'graduationDate' => false,
                'professional' => false,
                'firm' => false,
                'title' => false,
                'position' => false,
                'preferredChapter' => false,
                'credentials' => false,
                'aicpaNumber' => false,
                'certification' => false,
                'inStateCertificationNumber' => false,
                'inStateCertificationDate' => false,
                'outStateCertificationState' => false,
                'outStateCertificationNumber' => false,
                'outStateCertificationDate' => false,
                'directoryExclude' => false,
                'membership' => false,
                'sponsor' => false,
                'groupMemberships' => false,
                'interests' => false,
                'skills' => false,
                'specialNeeds' => false,
                'survey' => false,
                'memberSource' => false,
                'account' =>
                [
                    'preface' => null,
                    'addendum' => null,
                    'password' => true,
                    'passwordConfirmation' => true,
                ],
            ],
            'agreements' =>
            [
                'bylaws' => false,
                'terms' => false,
                'informationRelease' => false,
                'dataRelease' => false,
                'verify' => false,
            ],
        ],
    ],
];
