<?php

return array(
	'form' =>
	array(
		'name' => 'Default',
		'fields' =>
		array(
			'firm' => NULL,
			'person' =>
			array(
				'avatar' => false,
				'firstName' => true,
				'middleName' => false,
				'lastName' => true,
				'suffix' => false,
				'preferredName' => false,
				'priorName' => false,
				'spouse' => false,
				'birthDate' => false,
				'ethnicity' => false,
				'gender' => false,
				'pronoun' => false,
				'email' => NULL,
				'emailType' => false,
				'alternateEmail' => false,
				'alternateEmailType' => false,
				'emailExclude' => false,
				'phone' => false,
				'homePhone' => false,
				'mobilePhone' => false,
				'textExclude' => false,
				'officePhone' => false,
				'officeExtension' => false,
				'officeFax' => false,
				'address' =>
				array(
					'line1' => true,
					'line2' => false,
					'city' => true,
					'state' => true,
					'postalCode' => true,
					'country' => true,
				),
				'poAddress' =>
				array(
					'line1' => NULL,
					'postalCode' => NULL,
				),
				'contactPreferences' => false,
				'preferences' => false,
				'publicRegistration' => false,
				'social' => false,
				'links' =>
				array(
					'facebook' => false,
					'instagram' => false,
					'linkedin' => false,
					'twitter' => false,
				),
				'educational' => false,
				'school' => false,
				'schoolName' => false,
				'graduationDate' => false,
				'professional' => false,
				'firm' => false,
				'title' => false,
				'position' => false,
				'preferredChapter' => false,
				'credentials' => false,
				'aicpaNumber' => false,
				'certification' => false,
				'inStateCertificationNumber' => false,
				'inStateCertificationDate' => false,
				'outStateCertificationState' => false,
				'outStateCertificationNumber' => false,
				'outStateCertificationDate' => false,
				'directoryExclude' => false,
				'membership' => false,
				'sponsor' => false,
				'groupMemberships' => false,
				'interests' => false,
				'skills' => false,
				'specialNeeds' => false,
				'survey' => false,
				'memberSource' => false,
				'account' =>
				array(
					'preface' => NULL,
					'addendum' => NULL,
					'password' => true,
					'passwordConfirmation' => true,
				),
			),
			'agreements' =>
			array(
				'bylaws' => false,
				'terms' => false,
				'informationRelease' => false,
				'dataRelease' => false,
				'verify' => false,
			),
		),
	),
);
